services:
  - type: web
    name: yt-downloader-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd video_downloader_api/ && python manage.py runserver"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
